name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run:  cmake -S . -B build
    - run:  make -C build
    - run:  ./build/tests/Tests
